server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 14400
logging:
  level:
    org.springframework.web : debug
    sql: error
    jdbc: debug
    jdbc.sqlonly: debug
  file : ${user.home}/logs/product.log
  file.max-history: 9999999
  file.max-size : 100MB   
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mariadb://localhost:3306/blog
    username: cos
    password: cos1234
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      
  jackson:
    serialization:
      fail-on-empty-beans: false
      
cos:
  key: cos1234
